from config import (AL_LAMBDA_RATIO,
                    AMPLITUDE_FLOOR, BASE_CHANNELS, CONTOUR_SIGMA,
                    CONTOUR_THRESHOLD, HISTOGRAM_BINS, HISTOGRAM_SOFTNESS,
                    ITERATIONS, LEARNING_RATE, LOG_EVERY)


IMAGE_PATH = "123.png"
RESULTS_DIR = "results_projected_123"
