from config import (AMPLITUDE_FLOOR, BASE_CHANNELS, CONTOUR_SIGMA,
                    CONTOUR_THRESHOLD, HISTOGRAM_BINS, HISTOGRAM_SOFTNESS,
                    ITERATIONS, LEARNING_RATE, LOG_EVERY,
                    WEIGHT_AMPLITUDE, WEIGHT_AREA_RATIO, WEIGHT_BACKGROUND,
                    WEIGHT_HISTOGRAM)


IMAGE_PATH = "123.png"
RESULTS_DIR = "results_projected_123"
